steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "docker/Dockerfile.web"
      - "--build-arg"
      - "VITE_API_URL=https://aura-api-prod-v5nk7xhtoa-ew.a.run.app"
      - "-t"
      - "europe-west1-docker.pkg.dev/propane-berm-phnbb/aura/aura-web:v3"
      - "."

images:
  - "europe-west1-docker.pkg.dev/propane-berm-phnbb/aura/aura-web:v3"
