steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'docker/Dockerfile.api'
      - '-t'
      - 'europe-west1-docker.pkg.dev/propane-berm-phnbb/aura/aura-api:v6'
      - '.'

images:
  - 'europe-west1-docker.pkg.dev/propane-berm-phnbb/aura/aura-api:v6'
